include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    avoid_print: error

linter:
  rules:
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    omit_local_variable_types: false
    prefer_final_locals: true
    unawaited_futures: true
